{{- if .Values.limitRange.enabled }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "woocommerce.fullname" . }}-limits
  labels:
    {{- include "woocommerce.labels" . | nindent 4 }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.limitRange.default.cpu }}
        memory: {{ .Values.limitRange.default.memory }}
      defaultRequest:
        cpu: {{ .Values.limitRange.defaultRequest.cpu }}
        memory: {{ .Values.limitRange.defaultRequest.memory }}
      max:
        cpu: {{ .Values.limitRange.max.cpu }}
        memory: {{ .Values.limitRange.max.memory }}
{{- end }}
