apiVersion: v1
kind: Secret
metadata:
  name: {{ include "woocommerce.fullname" . }}-secrets
  labels:
    {{- include "woocommerce.labels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.mysql.rootPassword | quote }}
  mysql-password: {{ .Values.mysql.password | quote }}
  mysql-user: {{ .Values.mysql.user | quote }}
  mysql-database: {{ .Values.mysql.database | quote }}
  wp-admin-user: {{ .Values.wordpress.adminUser | quote }}
  wp-admin-password: {{ .Values.wordpress.adminPassword | quote }}
  wp-admin-email: {{ .Values.wordpress.adminEmail | quote }}
