{{- if .Values.wordpress.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "woocommerce.fullname" . }}-wordpress
  labels:
    {{- include "woocommerce.wordpress.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.wordpress.persistence.storageClass }}
  storageClassName: {{ .Values.wordpress.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.wordpress.persistence.size }}
{{- end }}
