apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform.fullname" . }}-backend
  labels:
    {{- include "platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: store-platform
    app.kubernetes.io/component: backend
